//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取返回值.
        /// </summary>
        internal static string C100 {
            get {
                return ResourceManager.GetString("C100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据插入成功.
        /// </summary>
        internal static string D000 {
            get {
                return ResourceManager.GetString("D000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名已存在.
        /// </summary>
        internal static string D001 {
            get {
                return ResourceManager.GetString("D001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该号码已注册，请直接登录.
        /// </summary>
        internal static string D002 {
            get {
                return ResourceManager.GetString("D002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码已过期.
        /// </summary>
        internal static string D003 {
            get {
                return ResourceManager.GetString("D003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证码错误.
        /// </summary>
        internal static string D004 {
            get {
                return ResourceManager.GetString("D004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据插入失败.
        /// </summary>
        internal static string D005 {
            get {
                return ResourceManager.GetString("D005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名不存在.
        /// </summary>
        internal static string D006 {
            get {
                return ResourceManager.GetString("D006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码错误.
        /// </summary>
        internal static string D007 {
            get {
                return ResourceManager.GetString("D007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据读取成功.
        /// </summary>
        internal static string D008 {
            get {
                return ResourceManager.GetString("D008", resourceCulture);
            }
        }
    }
}
